"""
Retail Sales Dashboard
======================
Interactive Streamlit dashboard that visualizes the output of the
retail sales ETL pipeline. Reads the processed CSVs and renders
KPIs, charts, and anomaly insights.

Run with:
    streamlit run dashboard.py
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Retail Sales Dashboard",
    page_icon="🛒",
    layout="wide",
    initial_sidebar_state="expanded",
)

PROCESSED_PATH = Path("data/processed")


# ── Data loading ──────────────────────────────────────────────────────────────
@st.cache_data
def load_data():
    """Loads the processed CSVs generated by the pipeline."""
    try:
        daily = pd.read_csv(PROCESSED_PATH / "daily_sales.csv", parse_dates=["order_date"])
        regional = pd.read_csv(PROCESSED_PATH / "sales_by_region.csv")
        top_products = pd.read_csv(PROCESSED_PATH / "top_products.csv")
        return daily, regional, top_products
    except FileNotFoundError:
        return None, None, None


# ── Header ────────────────────────────────────────────────────────────────────
st.title("🛒 Retail Sales Dashboard")
st.markdown(
    "Interactive view of the retail sales ETL pipeline output. "
    "Data flows through 5 quality gates before reaching this dashboard."
)

daily, regional, top_products = load_data()

if daily is None:
    st.warning(
        "⚠️ No processed data found. Run the pipeline first:\n\n"
        "```bash\npython data/generate_sample_data.py\npython pipeline.py\n```"
    )
    st.stop()


# ── KPI row ───────────────────────────────────────────────────────────────────
st.subheader("📊 Key Metrics")
col1, col2, col3, col4 = st.columns(4)

total_revenue = daily["total_revenue"].sum()
total_orders = int(daily["total_orders"].sum())
avg_order_value = total_revenue / total_orders if total_orders else 0
num_regions = len(regional)

col1.metric("Total Revenue", f"${total_revenue:,.0f}")
col2.metric("Total Orders", f"{total_orders:,}")
col3.metric("Avg Order Value", f"${avg_order_value:,.2f}")
col4.metric("Regions", num_regions)

st.divider()

# ── Charts row 1 ──────────────────────────────────────────────────────────────
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("📈 Daily Revenue Trend")
    fig_daily = px.line(
        daily,
        x="order_date",
        y="total_revenue",
        markers=True,
        labels={"order_date": "Date", "total_revenue": "Revenue ($)"},
    )
    fig_daily.update_layout(height=350, margin=dict(t=20, b=20))
    st.plotly_chart(fig_daily, use_container_width=True)

with col_right:
    st.subheader("🗺️ Revenue by Region")
    fig_region = px.bar(
        regional.sort_values("total_revenue", ascending=True),
        x="total_revenue",
        y="region",
        orientation="h",
        color="total_revenue",
        color_continuous_scale="Blues",
        labels={"total_revenue": "Revenue ($)", "region": "Region"},
    )
    fig_region.update_layout(height=350, margin=dict(t=20, b=20), coloraxis_showscale=False)
    st.plotly_chart(fig_region, use_container_width=True)

st.divider()

# ── Charts row 2 ──────────────────────────────────────────────────────────────
col_a, col_b = st.columns(2)

with col_a:
    st.subheader("🏆 Top 10 Products by Revenue")
    fig_products = px.bar(
        top_products.sort_values("total_revenue", ascending=True),
        x="total_revenue",
        y="product_id",
        orientation="h",
        color="total_revenue",
        color_continuous_scale="Greens",
        labels={"total_revenue": "Revenue ($)", "product_id": "Product"},
    )
    fig_products.update_layout(height=400, margin=dict(t=20, b=20), coloraxis_showscale=False)
    st.plotly_chart(fig_products, use_container_width=True)

with col_b:
    st.subheader("👥 Customers by Region")
    fig_customers = px.pie(
        regional,
        values="unique_customers",
        names="region",
        hole=0.4,
    )
    fig_customers.update_layout(height=400, margin=dict(t=20, b=20))
    st.plotly_chart(fig_customers, use_container_width=True)

st.divider()

# ── Data tables ───────────────────────────────────────────────────────────────
st.subheader("📋 Detailed Data")
tab1, tab2, tab3 = st.tabs(["Regional Summary", "Top Products", "Daily Sales"])

with tab1:
    st.dataframe(regional, use_container_width=True)
with tab2:
    st.dataframe(top_products, use_container_width=True)
with tab3:
    st.dataframe(daily, use_container_width=True)

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption(
    "Built by Gri-byte · Data flows through schema, volume, drop-rate, "
    "business-rule, and reconciliation gates before display."
)